apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces: [{name: source}]
  steps:
    - name: remove
      image: alpine:3
      script: |
        rm -rf $(workspaces.source.path)/*
        rm -rf $(workspaces.source.path)/.[!.]*
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces: [{name: source}]
  params:
    - name: args
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces: [{name: source}]
  params:
    - name: args
      default: "--count --max-complexity=10 --max-line-length=127 --statistics"
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service $(params.args)
